language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
- pypy3
env:
- DJANGO=">=1.4,<1.5"
- DJANGO=">=1.6,<1.7"
- DJANGO=">=1.7,<1.8"
install:
- pip install gitversion
- pip install "Django${DJANGO}"
- pip install .
- pip install coveralls
script:
- python setup.py test
after_success:
- coveralls
matrix:
  exclude:
  - python: 2.6
    env: DJANGO=">=1.7,<1.8"
  - python: 3.2
    env: DJANGO=">=1.4,<1.5"
  - python: 3.3
    env: DJANGO=">=1.4,<1.5"
  - python: pypy3
    env: DJANGO=">=1.4,<1.5"
